{
 "title": "Автотесты",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Время прогонов по неделям",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1w" ], "type": "time" }
     ],
     "measurement": "test run",
     "query": "SELECT sum(\"duration\")  / 3600000 AS \"automation\" FROM \"test run\" WHERE (\"is automation run\"::field = true) AND $timeFilter GROUP BY time(1w)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 3600000" ], "type": "math" },
       { "params": [ "automation" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "is automation run::field", "operator": "=", "value": "true" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1w" ], "type": "time" }
     ],
     "measurement": "test run",
     "query": "SELECT sum(\"duration\")  / 3600000 AS \"manual\" FROM \"test run\" WHERE (\"is automation run\"::field = false) AND $timeFilter GROUP BY time(1w)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 3600000" ], "type": "math" },
       { "params": [ "manual" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "is automation run::field", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Количество пройденных степов по неделям",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1w" ], "type": "time" }
     ],
     "measurement": "test run",
     "query": "SELECT sum(\"steps number\") AS \"automation\" FROM \"test run\" WHERE (\"is automation run\"::field = true) AND $timeFilter GROUP BY time(1w)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 3600000" ], "type": "math" },
       { "params": [ "automation" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "is automation run::field", "operator": "=", "value": "true" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1w" ], "type": "time" }
     ],
     "measurement": "test run",
     "query": "SELECT sum(\"steps number\") AS \"manual\" FROM \"test run\" WHERE (\"is automation run\"::field = false) AND $timeFilter GROUP BY time(1w)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 3600000" ], "type": "math" },
       { "params": [ "manual" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "is automation run::field", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Среднее время прохождения одного тест-степа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1w" ], "type": "time" }
     ],
     "measurement": "test run",
     "query": "SELECT sum(\"duration\")  / 60000 / sum(\"steps number\") FROM \"test run\" WHERE (\"is automation run\"::field = true) AND $timeFilter GROUP BY time(1w)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ],
      [
       { "params": [ "steps number" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "description::field", "operator": "=~", "value": "/Playwright/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1w" ], "type": "time" }
     ],
     "measurement": "test run",
     "query": "SELECT sum(\"duration\")  / 60000 / sum(\"steps number\") FROM \"test run\" WHERE (\"is automation run\"::field = false) AND $timeFilter GROUP BY time(1w)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ],
      [
       { "params": [ "steps number" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "description::field", "operator": "=~", "value": "/Playwright/" }
     ]
    }
   ]
  },
  {
   "title": "Статус автоматизации кейсов",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "measurement": "test case",
     "query": "SELECT \"automation status\" as \"case status\" FROM \"test case\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "automation status" ], "type": "field" }
      ],
      [
       { "params": [ "case id" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Пройденные тест-степы",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "measurement": "test run",
     "query": "SELECT \"steps number\" AS \"steps\", \"duration\"  / 3600000 AS \"duration\" FROM \"test run\" WHERE (\"is automation run\"::field = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "steps number" ], "type": "field" },
       { "params": [ "steps" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 3600000" ], "type": "math" },
       { "params": [ "duration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "description::field", "operator": "!~", "value": "/Playwright/" }
     ]
    },
    {
     "measurement": "test run",
     "query": "SELECT \"steps number\" AS \"steps\", \"duration\"  / 3600000 AS \"duration\" FROM \"test run\" WHERE (\"is automation run\"::field = false) AND $timeFilter",
     "select": [
      [
       { "params": [ "steps number" ], "type": "field" },
       { "params": [ "steps" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 3600000" ], "type": "math" },
       { "params": [ "duration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "description::field", "operator": "!=", "value": "/Playwright/" }
     ]
    }
   ]
  }
 ]
}